FROM node:11.14.0-alpine as webpack

LABEL maintainer="Martin Denk <ausdenk@gmail.com>"

# Add Tini and bash
RUN apk add --no-cache tini bash busybox-extras python build-base git openssh-client

ENV NODE_PATH /app/node_modules
ENV PATH $NODE_PATH/.bin:$PATH

WORKDIR /app/shared
COPY shared/package.json /app/shared/package.json
RUN npm install
WORKDIR /app/client
COPY client/package.json /app/client/package.json
COPY .ssh/id_rsa /tmp/id_rsa
RUN \
    chmod 600 /tmp/id_rsa && \
    eval $(ssh-agent) && \
    echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
    ssh-add /tmp/id_rsa && \
    npm install
COPY client /app/client
COPY shared /app/shared

RUN ./node_modules/.bin/webpack --config webpack.config.prod.js

#
# Client has been built, now we assemble the image for delivery
#

FROM nginx:1.17.0-alpine
RUN apk add --no-cache bash gettext
COPY --from=webpack /app/client/public /usr/share/nginx/html
COPY client/nginx/start-nginx.sh /
COPY client/nginx/config.js.template /
COPY client/nginx/default.conf /etc/nginx/conf.d
RUN chmod 755 /start-nginx.sh
EXPOSE 80
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && /start-nginx.sh
