type Query {
    match(id: ID!): Match!
    matches(filter: MatchFilter): [Match!]!
}

type Mutation {
    createMatch(input: CreateMatchInput!): Match!
    openMatch(id: ID!): Match!
    joinMatch(id: ID!): Match!
    startMatch(id: ID!): Match!
    pushActions(input: PushActionsInput!): Match!
}

type Subscription {
    playerJoined: Match!
}

type Match {
    id: ID!
    status: MatchStatus!
    handle: String!
    actions: [Action!]!
    players: [User!]!
    creator: User!
}

type Action {
    index: Int!
    randomSeed: String
    type: Int!
    payload: JSON
    match: Match!
    player: User
}

enum MatchStatus {
    SETTING_UP
    OPEN
    ACTIVE
    FINISHED
}

input MatchFilter {
    status: MatchStatus
}

input CreateMatchInput {
    handle: String!
}

input PushActionsInput {
    id: ID!
    actions: [ActionInput!]!
}

input ActionInput {
    type: Int!
    payload: JSON
}
