type Query {
    users: [User!]!
    me: User
}

type Mutation {
    createUser(input: CreateUserInput!): User!
    confirmUser(input: ConfirmUserInput!): LoginResult!
    login(input: LoginInput!): LoginResult!
    renewToken(input: RenewTokenInput!): LoginResult!
}

type User {
    id: ID!
    name: String!
    matches: [Match!]!
    inviteCode: String!
    active: Boolean!
    isAdmin: Boolean!
}

type LoginResult {
    authToken: String!
    renewalToken: String!
}

input CreateUserInput {
    name: String!
}

input ConfirmUserInput {
    name: String!
    email: String!
    inviteCode: String!
    password: String!
}

input LoginInput {
    name: String!
    password: String!
}

input RenewTokenInput {
    renewalToken: String!
}
