
const states = {
    BID_FOR_TURN_ORDER: 0,
    MOVE_PLAYER_MARKER_TO_BID_ORDER_TRACK: 1,
    SELECT_TILE_FOR_MOVEMENT: 2,
    SELECT_TILE_FOR_PLACEMENT: 3,
    SELECT_MEEPLE_TO_PLACE: 4,
    PLACE_PALACE: 5,
    SELECT_MEEPLE_TO_KILL: 6,
    // GO_TO_SMALL_MARKET: 7,
    // SELECT_RESOURCES_FROM_MARKET: 8,
    // COLLECT_DJINN: 9,
    // SELECT_DJINN_FROM_DISPLAY: 10,
    // SELL_RESOURCES: 11,
    END_TURN: 12,
    EXECUTE_MEEPLE_ACTION: 13,
    SELECT_FAKIRS_FOR_MEEPLE_ACTION: 14,
    COLLECT_MARKET_RESOURCES: 15,
    COLLECT_GOLD_COINS: 16,
    TAKE_CONTROL_OF_TILE: 17,
    PLACE_PALM_TREE: 18,
    // GO_TO_BIG_MARKET: 19,
    TAKE_CONTROL_OF_TILE_AFTER_ASSASSINATION: 20,
};

module.exports = {
    actions: require('./five-tribes/actions'),
    assets: require('./five-tribes/assets'),
    states: require('./five-tribes/states'),
};
